### ISSUE TITLE
Slow addition of TFs

### ISSUE THREAD

**Issue by agrayver** [MTgeophysics/mtpy-v2#44]
I'm trying to create a MTCollection for a large data set (> 1000 edi files). Using a loop with *mt_object.read(fn) /     md.add_station(mt_object)*, it takes > 5 hours. It slows down with iteration, as if there is some reinitialization/copy every time the *add* function is called. 

Is this a feature or is there perhaps a more efficient bulk read function?

**Comment by kujaku11** [comment]
@agrayver Interesting, I just tried something similar and it was also slow.  There must be a bottleneck somewhere and it is likely to do with setting up the groups for each station.  In mine there were a lot of EDI files that had no survey name, so MTCollection kept creating `unknown_survey_##` and that seemed to slow it down quite a bit.  I'll work on some efficiencies hopefully in the next week or so.

**Comment by kujaku11** [comment]
@agrayver I updated the code so that building a `MTCollection` is much faster (starting with v2.0.10).  It should take between .5-5 seconds to add a transfer function depending on the metadata inside.  One way to speed it up is to set survey to be the same for all transfer functions if that makes sense to do so.  

```python
from mtpy import MTCollection

with MTCollection() as mc:
    mc.open_collection("path/to/collection.h5"
    mc.add_tf(list_of_transfer_functions, new_survey="common_survey_name")
``` 

If that works for you feel free to close this issue.

**Comment by agrayver** [comment]
thanks for looking into this
